#!/usr/bin/env bash
# Open /etc/passwd for reading
while IFS=: read -r username _ uid _ _ home _; do
    # Print username, user ID, and home directory
    echo "$username:$uid:$home"
done < /etc/passwd
