#!/usr/bin/env bash
# Set IFS to ':' to read fields separated by ':'
while IFS=: read -r username _ uid gid _ home shell; do
    # Extract additional user information from /etc/passwd
    info=$(grep "^$username:" /etc/passwd | cut -d: -f5)

    # Retrieve the user's encrypted password (normally stored in /etc/shadow)
    password=$(grep "^$username:" /etc/shadow | cut -d: -f2)

    # Format the output based on extracted fields
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
