#!/usr/bin/env bash
# Initialize the counter variable
counter=1

# Start the while loop to iterate from 1 to 20
while (( counter <= 20 )); do
    # Check if the current number matches any of the special cases
	    case $counter in
                4)
                echo "$counter"
                echo "Bad luck from China"
                ;;
                9)
                echo "$counter"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "Bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    
    # Increment the counter
    ((counter++))
done
~                                                                                                                           
~                           
