#!/usr/bin/env bash
#Cogsworth's brain
hour=0
minute=1
count=0

while [ $count -lt 70 ]; do
    formatted_hour=$(printf "%02d" $hour)
    formatted_minute=$(printf "%02d" $minute)
    
    echo "$formatted_hour:$formatted_minute"
    
    count=$((count + 1))
    minute=$((minute + 1))
    
    if [ $minute -gt 59 ]; then
        minute=1
        hour=$((hour + 1))
    fi
done

