#!/usr/bin/env bash
#Cogsworth's brain
hour=0
count=0

while [ $count -lt 13 ]; do
    printf "%02d\n" $hour  # Print hour with leading zeros if necessary
    count=$((count + 1))
    hour=$((hour + 1))
done

